### ISSUE TITLE
Fatal Error U1077; return code 0x1

### ISSUE THREAD

**Issue by snrgarb** [nirai-compiler/python#3]
Microsoft (R) Program Maintenance Utility Version 12.00.21005.1
Copyright (C) Microsoft Corporation.  All rights reserved.

```
    echo Building...
```

Building...
        msbuild /m:4 python.vcxproj "/p:Configuration=Release"
Microsoft (R) Build Engine version 12.0.31101.0
[Microsoft .NET Framework, version 4.0.30319.34209]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 6/16/2015 11:18:40 AM.
     1>Project "C:\Users\Gabriel\Music\nirari-compiler\python\python.vcxproj" o
       n node 1 (default targets).
     1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Pla
       tform.targets(64,5): error MSB8020: The build tools for Visual Studio 20
       10 (Platform Toolset = 'v100') cannot be found. To build using the v100
       build tools, please install Visual Studio 2010 build tools.  Alternative
       ly, you may upgrade to the current Visual Studio tools by selecting the
       Project menu or right-click the solution, and then selecting "Upgrade So
       lution...". [C:\Users\Gabriel\Music\nirari-compiler\python\python.vcxpro
       j]
     1>Done Building Project "C:\Users\Gabriel\Music\nirari-compiler\python\pyt
       hon.vcxproj" (default targets) -- FAILED.

Build FAILED.

```
   "C:\Users\Gabriel\Music\nirari-compiler\python\python.vcxproj" (default
   target) (1) ->
   (PlatformPrepareForBuild target) ->
     C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.P
   latform.targets(64,5): error MSB8020: The build tools for Visual Studio
   2010 (Platform Toolset = 'v100') cannot be found. To build using the v10
   0 build tools, please install Visual Studio 2010 build tools.  Alternati
   vely, you may upgrade to the current Visual Studio tools by selecting th
   e Project menu or right-click the solution, and then selecting "Upgrade
   Solution...". [C:\Users\Gabriel\Music\nirari-compiler\python\python.vcxp
   roj]

0 Warning(s)
1 Error(s)
```

Time Elapsed 00:00:00.12
NMAKE : fatal error U1077: '"C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.EXE
"' : return code '0x1'
Stop.

**Comment by loblao** [comment]
You are using Visual Studio 2013 (12.0) which is not supported. Only Visual Studio 2010 is supported at the moment.
