### ISSUE TITLE
Can't compile embedded Python on Windows 7 64 bit using anything

### ISSUE THREAD

**Issue by compile0219** [nirai-compiler/python#4]
Hi. I've tried for hours and hours and almost 2 days now with sleep in between to get Nirai working (without a tutorial/detailed readme) and it's honestly been really rough but I got it down to a point of where I'm almost done with building it from the source. I have Panda3D compiled, and I'm just waiting to get a proper pythonembed.lib built to finish up everything else.

I heard this project is VS 2010 based but whenever I try using that or anything less than 2013 it errors on saying it needs "v120 builds tools" to continue (CMake file issue?), which is 2013. Using 2013 it will build properly(?) but then I get more errors, did some more tweaking, and finally got it down to this (exception with --compile-cxx after compiling pythonembed.lib in 2013):

http://i.imgur.com/ZIJ3Ntx.png

I have a feeling it's due to mix-up of 32-bit and 64-bit but even trying different methods for switching those around I haven't gotten any good results and I'm finally stuck on one I can't fix myself.

How do I fix this? I've tried a billion different ways with different Visual Studios and command prompt variants to no avail. Thank you. The error above is the closest I've gotten.

**Comment by mfwass** [comment]
Did you use Nirai's panda3d and run postbuild?

The directory structure of Nirai is very specific as well. Make sure the paths are correct. `make.py` has set paths where to find the files along with `niraitools.py`.

**Comment by compile0219** [comment]
Yes, and yes.

I think since I got this far all that should be okay regarding the paths (I think I'm close to done?), but just incase my directory structure is:

Main Folder:
/panda3d
/python
/sample-project (make.py & niraitools.py are in a subdirectory of this, I dragged and dropped pythonembed.lib into their folder (or also put the compiled path to here with no drag, so it really shouldn't be an issue, same results) as well as the aes.pyd, is this bad?)
/src

Right now I'm just trying to get it running using the sample project.

**Comment by loblao** [comment]
`aes.pyd` should be in `/src`, but copying it to somewhere else is harmless. `libpythonembed.lib` should be in `/python` and copying it can be problematic (ie. path conflict), since niraitools expects it to be in `/python`. However, it seems like your is from using VS2013. You have to build everything with VS2010.

> whenever I try using that or anything less than 2013 it errors on saying it needs "v120 builds tools" to continue (CMake file issue?), which is 2013. 

I don't quite understand this, but you can tell CMake to use vs2010 this way:

> cmake -G "Visual Studio 10 2010" path/to/python

**Comment by compile0219** [comment]
When forcing VS2010 with CMake:

http://pastebin.com/u8CZstWc

**Comment by loblao** [comment]
What version of CMake are you using? Either CMake or VS2010 is corrupted.

**Comment by compile0219** [comment]
CMake is the newest version, I downloaded it recently. I'll try reinstalling VS2010 sometime today. Is there a certain package I need?

**Comment by mfwass** [comment]
Try using the CMake GUI application. It's a bit more easy to use in my opinion considering you can have a visualization of what you're configuring/generating. It'll give you the option of choosing your compiler, chose the Visual Studio 2010 one.

https://cmake.org/download/

**Comment by compile0219** [comment]
Crashed in the same manner using CMake with its GUI. I'll try a fresh install of VS2010 if you suggest it still after reading these.

CMakeOutput.log: http://pastebin.com/6Gaa1NRC (Seems to have 0 fails in here?)

CMakeError.log: http://pastebin.com/Zs9iZeZD

**Comment by compile0219** [comment]
Any thoughts guys? Gonna go ahead and try reinstalling tonight if I get time. Thanks!

**Comment by jwcotejr** [comment]
Go ahead and try reinstalling Visual Studio 2010, I'd say.

**Comment by compile0219** [comment]
I'm removing (uninstalling, of course) pretty much everything VS 2010 related as I don't need it anyways. What EXACTLY do I need so I get the right thing? 32 bit version? Links would be appreciated. Any SDK needed too? Thanks again guys!

**Comment by compile0219** [comment]
Alright, uninstalled and installed VS2010 (ultimate) again with no change at all. Still an error on the COFF conversion or whatever.

Does anybody have a compiled pythonembed.lib around? I don't really have much interest in changing anything around in there so I would assume I'd only really need to do that once anyhow and this step is hindering the rest, hopefully after that everything will go pretty well.

**Comment by jwcotejr** [comment]
We usually don't provide pre-compiled binaries for compatibility purposes.

**Comment by compile0219** [comment]
Hmm. Any other ideas, then?

**Comment by compile0219** [comment]
Fixed that by using an alternate cvtres.exe in the VS folders. Now I'm onto another error but is only giving me an output log this time (shown below), and not an error log file (hard to tell what's wrong here):

http://pastebin.com/YLRaPxSZ

**Comment by compile0219** [comment]
Bump. Any ideas? :)

**Comment by compile0219** [comment]
Fixed this particular issue by using a brand-new fresh Windows 7 install on another machine, then installing .NET Framework 4, Windows 7.1 SDK, Panda3D (for Python, but I like to have both at once), and CMake. Must have been some weird conflicting software. Onto the next issue...
