### ISSUE TITLE
Installing python

### ISSUE THREAD

**Issue by judge2020** [nirai-compiler/python#5]
How do I run an install command on this? Following the guide in SRC, I run 

    Cmake . && make

This builds it, however does not install it.

There is also no install target in the makefile so make install does not work.

Running macOS 10.12

**Comment by mfwass** [comment]
This python is not meant to be used directly in the command-line, this python is only meant to be used with Nirai's compiled binary.  Make sure aespyd is compiled.

Usage instructions are listed in our [README](https://github.com/nirai-compiler/src/blob/master/README.md#usage) in the src repo.

**Comment by judge2020** [comment]
Thanks for the quick reply, I'm having a problem compiling panda and considered *not* using nirai's python might be the problem. 

The error is that it can't find libp3dtool even though the no-pandatool option is passed to makepanda (I have not modified compile.sh whatsoever)

**Comment by mfwass** [comment]
May you post your full traceback?

**Comment by judge2020** [comment]
I'm actually working on building through travis, maybe that's the problem here.

(verbose mode) https://pastebin.com/52TKqK3u

**Comment by mfwass** [comment]
Try with fewer threads.  That might be causing the issue with Panda.

**Comment by judge2020** [comment]
Still seems to be trying to reference it with no explicit threads declared. I might try just building pandatool and including it no matter what.

**Comment by judge2020** [comment]
Yeah that doesn't work. For some reason it straight up ignores no-pandatool.
